/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bingo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.mail.MessagingException;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;

/**
 *
 * @author Jonas
 */
public class GuiFiliaalIndex extends javax.swing.JFrame {

    /**
     * Creates new form GuiKlantIndex
     */
    private static final GuiFiliaalIndex guiKI = new GuiFiliaalIndex();
    private DefaultListModel model;
    private DefaultListModel model2;
    private Filiaal fn;
    ArrayList<Account> accs;
    ArrayList<Account> curAccs;
    ArrayList<Spaarkaart> sks;
    ArrayList<Spaarkaart> curSks;
    ArrayList<Account> major;
    
    public static GuiFiliaalIndex getInstance()
    {
        return guiKI;
    }
    
    public GuiFiliaalIndex() 
    {
        initComponents();
        lstSearch.setVisible(false);
        lstSks.setVisible(false);
    }
    
    public void setFiliaal(Filiaal fi)
    {
        this.fn = fi;
        MySQL sql = new MySQL();
        accs = sql.getAccounts();
        curAccs = accs;
        sks = sql.getSpaarkaarten();
        curSks = sks;
        major = sql.getMajor(fn.getWinkel());
        setMajor();
        lblNaam.setText(fn.getNaam());
        lblAdres.setText(fn.getStraatFiliaal() + " " + fn.getHuisnummerFiliaal() + ", " + fn.getPostcodeFiliaal() + " " + fn.getStadFiliaal());
        lblTelefoon.setText(fn.getTelefoonFiliaal());
        lblWinkel.setText(fn.getWinkelNaam());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jButton7 = new javax.swing.JButton();
        ppmSearch = new javax.swing.JPopupMenu();
        ppmSks = new javax.swing.JPopupMenu();
        pnlInfo = new javax.swing.JPanel();
        lblNaam = new javax.swing.JLabel();
        lblAdres = new javax.swing.JLabel();
        lblTelefoon = new javax.swing.JLabel();
        lblFiliaalvan = new javax.swing.JLabel();
        lblWinkel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSearch = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSks = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        lblMaj1 = new javax.swing.JLabel();
        lblMaj2 = new javax.swing.JLabel();
        lblMaj3 = new javax.swing.JLabel();
        lblMaj4 = new javax.swing.JLabel();
        lblMaj5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnVerTot = new javax.swing.JButton();
        btnVerPtn = new javax.swing.JButton();
        btnAss = new javax.swing.JButton();
        jbutten8 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jButton7.setText("jButton7");

        JMenuItem bew = new JMenuItem("Bewerken");
        ppmSearch.add(bew);

        bew.addActionListener(new ActionListener()
            {
                @Override
                public void actionPerformed(ActionEvent actionEvent)
                {
                    Account acc = curAccs.get(lstSearch.getSelectedIndex());
                    bingo.GuiKlantBew guiKB = bingo.GuiKlantBew.getInstance();
                    guiKB.setAccount(acc);
                    guiKB.setFI(true);
                    setVisible(false);
                    guiKB.setVisible(true);
                }
            });

            JMenuItem scan = new JMenuItem("Scannen");
            JMenuItem bewe = new JMenuItem("Bewerken");
            ppmSks.add(scan);
            ppmSks.add(bewe);

            scan.addActionListener(new ActionListener()
                {
                    @Override
                    public void actionPerformed(ActionEvent actionEvent)
                    {
                        Spaarkaart sk = curSks.get(lstSks.getSelectedIndex());
                        bingo.GuiVerkoop guiVK = bingo.GuiVerkoop.getInstance();
                        guiVK.setSpaarkaart(sk);
                        guiVK.setFiliaal(fn);
                        guiVK.updateTable();
                        setVisible(false);
                        guiVK.setVisible(true);
                    }
                });

                bewe.addActionListener(new ActionListener()
                    {
                        @Override
                        public void actionPerformed(ActionEvent actionEvent)
                        {
                            Spaarkaart sk = curSks.get(lstSks.getSelectedIndex());
                            bingo.GuiSpaarkaartBew guiSkB = bingo.GuiSpaarkaartBew.getInstance();
                            guiSkB.setSk(sk);
                            guiSkB.setFI(true);
                            setVisible(false);
                            guiSkB.setVisible(true);
                        }
                    });

                    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                    pnlInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));

                    lblNaam.setText("Naam");

                    lblAdres.setText("Adres");

                    lblTelefoon.setText("Telefoon");

                    lblFiliaalvan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                    lblFiliaalvan.setText("Filiaal van:");

                    lblWinkel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                    lblWinkel.setText("Winkel");

                    javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
                    pnlInfo.setLayout(pnlInfoLayout);
                    pnlInfoLayout.setHorizontalGroup(
                        pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlInfoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNaam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAdres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTelefoon, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                            .addGap(304, 304, 304)
                            .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblWinkel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFiliaalvan, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                            .addGap(136, 136, 136))
                    );
                    pnlInfoLayout.setVerticalGroup(
                        pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlInfoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNaam)
                                .addComponent(lblFiliaalvan))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAdres)
                                .addComponent(lblWinkel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblTelefoon)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    );

                    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Zoeken"));

                    txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                            txtSearchKeyReleased(evt);
                        }
                    });

                    model = new DefaultListModel();
                    lstSearch.setModel(model);
                    lstSearch.addMouseListener(new MouseAdapter()
                        {
                            @Override
                            public void mousePressed(MouseEvent e)  {check(e);}
                            public void mouseReleased(MouseEvent e) {check(e);}

                            public void check(MouseEvent e)
                            {
                                if (e.isPopupTrigger())
                                {
                                    lstSearch.setSelectedIndex(lstSearch.locationToIndex(e.getPoint()));
                                    ppmSearch.show(lstSearch, e.getX(), e.getY());
                                }
                            }
                        });
                        jScrollPane1.setViewportView(lstSearch);

                        model2 = new DefaultListModel();
                        lstSks.setModel(model2);
                        lstSks.addMouseListener(new MouseAdapter()
                            {
                                @Override
                                public void mousePressed(MouseEvent e)  {check(e);}
                                public void mouseReleased(MouseEvent e) {check(e);}

                                public void check(MouseEvent e)
                                {
                                    if (e.isPopupTrigger())
                                    {
                                        lstSks.setSelectedIndex(lstSks.locationToIndex(e.getPoint()));
                                        ppmSks.show(lstSks, e.getX(), e.getY());
                                    }
                                }
                            });
                            jScrollPane2.setViewportView(lstSks);

                            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                            jPanel2.setLayout(jPanel2Layout);
                            jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jScrollPane2))
                                    .addContainerGap())
                            );
                            jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(12, Short.MAX_VALUE))
                            );

                            jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Mayor"));

                            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                            jPanel3.setLayout(jPanel3Layout);
                            jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblMaj5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblMaj1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblMaj3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                            .addComponent(lblMaj2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(lblMaj4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap(69, Short.MAX_VALUE))
                            );
                            jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblMaj1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblMaj2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblMaj3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblMaj4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblMaj5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(80, Short.MAX_VALUE))
                            );

                            jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Klanten"));

                            jButton1.setText("Scannen");
                            jButton1.addActionListener(new java.awt.event.ActionListener() {
                                public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton1ActionPerformed(evt);
                                }
                            });

                            jButton2.setText("Bewerken");
                            jButton2.addActionListener(new java.awt.event.ActionListener() {
                                public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton2ActionPerformed(evt);
                                }
                            });

                            jButton3.setText("Toevoegen");
                            jButton3.addActionListener(new java.awt.event.ActionListener() {
                                public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jButton3ActionPerformed(evt);
                                }
                            });

                            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                            jPanel4.setLayout(jPanel4Layout);
                            jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addContainerGap())
                            );
                            jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(18, Short.MAX_VALUE))
                            );

                            jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Rapporten"));

                            btnVerTot.setText("Verkopen totaal");
                            btnVerTot.addActionListener(new java.awt.event.ActionListener() {
                                public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    btnVerTotActionPerformed(evt);
                                }
                            });

                            btnVerPtn.setText("Verkopen (punten)");
                            btnVerPtn.addActionListener(new java.awt.event.ActionListener() {
                                public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    btnVerPtnActionPerformed(evt);
                                }
                            });

                            btnAss.setText("Assortiment");
                            btnAss.addActionListener(new java.awt.event.ActionListener() {
                                public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    btnAssActionPerformed(evt);
                                }
                            });

                            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                            jPanel5.setLayout(jPanel5Layout);
                            jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnAss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnVerPtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnVerTot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addContainerGap())
                            );
                            jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(btnVerTot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnVerPtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)
                                    .addComponent(btnAss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(16, 16, 16))
                            );

                            jbutten8.setText("Hoofdmenu");
                            jbutten8.addActionListener(new java.awt.event.ActionListener() {
                                public void actionPerformed(java.awt.event.ActionEvent evt) {
                                    jbutten8ActionPerformed(evt);
                                }
                            });

                            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                            getContentPane().setLayout(layout);
                            layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jbutten8)))
                                    .addContainerGap())
                            );
                            layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbutten8))
                            );

                            pack();
                        }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GuiScan guiScan = GuiScan.getInstance();
        guiScan.setFiliaal(fn);
        setVisible(false);
        guiScan.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVerTotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTotActionPerformed
        GuiFiliaalVerkopenTotaal guiKVT = GuiFiliaalVerkopenTotaal.getInstance();
        guiKVT.setFiliaal(fn);
        guiKVT.setWI(false);
        guiKVT.updateTable();
        setVisible(false);
        guiKVT.setVisible(true);
    }//GEN-LAST:event_btnVerTotActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        GuiNieuweKlant guiNK = GuiNieuweKlant.getInstance();        
        setVisible(false);
        guiNK.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GuiKlanten guiK = GuiKlanten.getInstance();
        guiK.updateTable();
        setVisible(false);
        guiK.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnVerPtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPtnActionPerformed
        GuiFiliaalVerkopenPunten guiKVP = GuiFiliaalVerkopenPunten.getInstance();
        guiKVP.setFiliaal(fn);
        guiKVP.setWI(false);        
        guiKVP.updateTable();        
        setVisible(false);
        guiKVP.setVisible(true);
    }//GEN-LAST:event_btnVerPtnActionPerformed

    private void btnAssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssActionPerformed
        GuiFiliaalRapportAssortiment guiKRA = GuiFiliaalRapportAssortiment.getInstance();
        guiKRA.setFiliaal(fn);
        guiKRA.setWI(false);
        guiKRA.updateTable();
        setVisible(false);
        guiKRA.setVisible(true);
    }//GEN-LAST:event_btnAssActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String search = txtSearch.getText();
        if(!search.equals(""))
        {
            lstSearch.setVisible(true);
            curAccs = zoekAccounts(search);
            initList(curAccs);
            lstSks.setVisible(true);
            curSks = zoekSpaarkaarten(search);
            initSks(curSks);
        }
        else
        {
            lstSearch.setVisible(false);
            lstSks.setVisible(false);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void jbutten8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutten8ActionPerformed
        
        GuiHoofdmenu guiHM = GuiHoofdmenu.getInstance();
        setVisible(false);
        guiHM.setVisible(true);
            
    }//GEN-LAST:event_jbutten8ActionPerformed

    private void ppmSearchActionPerformed(java.awt.event.ActionEvent evt)    
    {
    }
    
    public ArrayList<Account> zoekAccounts(String search)
    {
        ArrayList<Account> zkList = new ArrayList<Account>();
        search = search.toLowerCase();
        System.out.println(search);
        for(Account a : accs)
        {
            if(a.getNaam().toLowerCase().startsWith(search) || Integer.toString(a.getID()).startsWith(search))
            {
                zkList.add(a);
            }
        }
        return zkList;
    }    

    public ArrayList<Spaarkaart> zoekSpaarkaarten(String search)
    {
        ArrayList<Spaarkaart> zkList = new ArrayList<Spaarkaart>();
        search = search.toLowerCase();
        System.out.println(search);
        for(Spaarkaart a : sks)
        {
            if(a.getSNaam().toLowerCase().startsWith(search) || a.getNaam().toLowerCase().startsWith(search) || a.getVoornaam().toLowerCase().startsWith(search) || Integer.toString(a.getSId()).startsWith(search))
            {
                zkList.add(a);
            }
        }
        return zkList;
    }       
    
    public void initList(ArrayList<Account> acList)
    {
        DefaultListModel bmodel = (DefaultListModel) lstSearch.getModel();
        bmodel.removeAllElements();
        for(Account a : acList)
        {
            bmodel.addElement("[Account " + a.getID() + "] " + a.getNaam() + ", " + a.getStad());
            this.curAccs = acList;
        }
        lstSearch.setVisible(true);
    }

    public void initSks(ArrayList<Spaarkaart> skList)
    {
        DefaultListModel bmodel = (DefaultListModel) lstSks.getModel();
        bmodel.removeAllElements();
        for(Spaarkaart a : skList)
        {
            bmodel.addElement("[Spaarkaart " + a.getSId() + "] " + a.getSNaam() + " " + a.getVoornaam() + " (" + a.getNaam() + ")");
            this.curSks = skList;
        }
        lstSks.setVisible(true);
    }    
    
    public void setMajor()
    {
        System.out.println(major.size());
        if(major.size() >= 1)
        {
            lblMaj1.setText("1. " + major.get(0).getNaam());
        }
        if(major.size() >= 2)
        {
            lblMaj2.setText("2. " + major.get(1).getNaam());
        }
        if(major.size() >= 3)
        { 
            lblMaj3.setText("3. " + major.get(2).getNaam());
        }
        if(major.size() >= 4)
        {
            lblMaj4.setText("4. " + major.get(3).getNaam());
        }
        if(major.size() >= 5)
        {
            lblMaj5.setText("5. " + major.get(4).getNaam());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAss;
    private javax.swing.JButton btnVerPtn;
    private javax.swing.JButton btnVerTot;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbutten8;
    private javax.swing.JLabel lblAdres;
    private javax.swing.JLabel lblFiliaalvan;
    private javax.swing.JLabel lblMaj1;
    private javax.swing.JLabel lblMaj2;
    private javax.swing.JLabel lblMaj3;
    private javax.swing.JLabel lblMaj4;
    private javax.swing.JLabel lblMaj5;
    private javax.swing.JLabel lblNaam;
    private javax.swing.JLabel lblTelefoon;
    private javax.swing.JLabel lblWinkel;
    private javax.swing.JList lstSearch;
    private javax.swing.JList lstSks;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPopupMenu ppmSearch;
    private javax.swing.JPopupMenu ppmSks;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
