package bingo;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonas
 */
public class GuiFilialen extends javax.swing.JFrame {

    /**
     * Creates new form GuiArtikels
     */
    
    private static final GuiFilialen guiFi = new GuiFilialen();
    protected Winkel wn;
    ArrayList<Filiaal> fiList;
    ArrayList<Filiaal> curList;
    
    public GuiFilialen() 
    {
        GuiWinkelIndex guiWI = GuiWinkelIndex.getInstance();
        wn = guiWI.getWinkel();
        initComponents();
    }
    
    public static GuiFilialen getInstance()
    {
        return guiFi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFilialen = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DefaultTableModel model = new DefaultTableModel()
        {
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };
        System.out.println("test1");
        tblFilialen.setModel(model);
        MySQL mySQL = new MySQL();
        try
        {
            System.out.println("test3");
            fiList = mySQL.getFilialen(wn.getWinkelID());
            System.out.println("test4");
            curList = fiList;
            model.setColumnIdentifiers(new String[]{"ID", "Naam", "Straat", "Nummer", "Postcode", "Stad", "Telefoon" });
            for(Filiaal fi : fiList)
            {
                System.out.println(fi.getNaam());
                model.addRow(new Object[]{fi.getIdFiliaal(), fi.getNaam(), fi.getStraatFiliaal(), fi.getHuisnummerFiliaal(), fi.getPostcodeFiliaal(), fi.getStadFiliaal(), fi.getTelefoonFiliaal()});
            }
        }
        catch(SQLException e)
        {
        }
        jScrollPane1.setViewportView(tblFilialen);

        jButton1.setText("Bewerken");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jButton2.setText("Terug");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(tblFilialen.getSelectedRow());
        System.out.println(curList.get(tblFilialen.getSelectedRow()).getNaam());  
        GuiFiliaalBew guiFB = GuiFiliaalBew.getInstance();
        if(curList.isEmpty())
        {
            guiFB.setFiliaal(fiList.get(tblFilialen.getSelectedRow()));
            System.out.println("CL: " + curList.get(tblFilialen.getSelectedRow()).getNaam());
        }
        else
        {
            guiFB.setFiliaal(curList.get(tblFilialen.getSelectedRow()));
            System.out.println("AL: " + curList.get(tblFilialen.getSelectedRow()).getNaam());
        }
        guiFB.setWinkel(wn);
        guiFB.setAdmin(false);
        guiFB.setWI(false);
        setVisible(false);
        guiFB.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String search = txtSearch.getText();
        System.out.println(search);
        if(search.equals(""))
        {
            initTable(fiList);
        }
        else
        {
            ArrayList<Filiaal> zkList = zoekArtikels(search);
            initTable(zkList);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    public void updateTable()
            {
                System.out.println("test3");
                DefaultTableModel model = (DefaultTableModel) tblFilialen.getModel();
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--)
        {
            model.removeRow(i);
        }
                MySQL mySQL = new MySQL();
        try
        {
     System.out.println("test4");
      fiList = mySQL.getFilialen(wn.getWinkelID());
     
        curList = fiList;
        model.setColumnIdentifiers(new String[]{"ID", "Naam", "Straat", "Nummer", "Postcode", "Stad", "Telefoon" });
         for(Filiaal fi : fiList)
         {
        
        model.addRow(new Object[]{fi.getIdFiliaal(), fi.getNaam(), fi.getStraatFiliaal(), fi.getHuisnummerFiliaal(), fi.getPostcodeFiliaal(), fi.getStadFiliaal(), fi.getTelefoonFiliaal()});
          }
        }
        catch(SQLException e)
     {
      }  
            }
    
    
    
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        GuiWinkelIndex guiKI = GuiWinkelIndex.getInstance();
        setVisible(false);
        guiKI.setVisible(true);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public ArrayList<Filiaal> zoekArtikels(String kw)
    {
        ArrayList<Filiaal> zkList = new ArrayList<Filiaal>();
        for(Filiaal fi : fiList)
        {
            if(fi.getNaam().toLowerCase().startsWith(kw))
            {
                zkList.add(fi);
            }
        }
        return zkList;
    }
    
    public void initTable(ArrayList<Filiaal> aList)
    {
        DefaultTableModel model = (DefaultTableModel) tblFilialen.getModel();
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--)
        {
            model.removeRow(i);
        }
        for(Filiaal fi : aList)
        {
            model.addRow(new Object[]{fi.getIdFiliaal(), fi.getNaam(), fi.getStraatFiliaal(), fi.getHuisnummerFiliaal(), fi.getPostcodeFiliaal(), fi.getStadFiliaal(), fi.getTelefoonFiliaal() });
            this.curList = aList;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiFilialen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiFilialen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiFilialen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiFilialen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiFilialen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFilialen;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
