/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bingo;

import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Guillaume
 */
public class GuiKlantBew extends javax.swing.JFrame {

    /**
     * Creates new form GuiKlantNieuweKlantPrivé
     */
    private static final GuiKlantBew guiNK = new GuiKlantBew();
    private boolean isBedrijf = false;
    private JFileChooser fc;
    private Account ac;
    private boolean fi = false;

    public static GuiKlantBew getInstance()
    {
        return guiNK;
    }
    
    public GuiKlantBew() {
        initComponents();
    }
    
    public void setAccount(Account a)
    {
        this.ac = a;
        txtNaam.setText(a.getNaam());
        txtStraat.setText(a.getStraat());
        txtNummer.setText(a.getNummer());
        txtStad.setText(a.getStad());
        txtPostcode.setText(a.getPostcode());
        txtEmail.setText(a.getEmail());
        if(a.getBedrijf() == false)
        {
            isBedrijf = false;
            cBox.setSelectedIndex(0);
            lblBTW.setVisible(false);
            txtBTW.setVisible(false);
            txtDag.setVisible(true);
            txtDag.setText(Integer.toString(a.getGebD()));
            txtMaand.setVisible(true);
            txtMaand.setText(Integer.toString(a.getGebM()));
            txtJaar.setVisible(true);
            txtJaar.setText(Integer.toString(a.getGebJ()));
            lblSlash1.setVisible(true);
            lblSlash2.setVisible(true);
            lblGD.setVisible(true);
        }
        else
        {
            isBedrijf = true;
            cBox.setSelectedIndex(1);
            lblBTW.setText("BTW-nummer");
            lblBTW.setVisible(true);
            txtBTW.setText(a.getBtw());
            txtBTW.setVisible(true);
            txtDag.setVisible(false);
            txtMaand.setVisible(false);
            txtJaar.setVisible(false);
            lblSlash1.setVisible(false);
            lblSlash2.setVisible(false);
            lblGD.setVisible(false);
        }        
    }
    
    public void setFI(boolean b)
    {
        this.fi = b;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaam = new javax.swing.JLabel();
        lblBTW = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNaam = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtBTW = new javax.swing.JTextField();
        txtStraat = new javax.swing.JTextField();
        txtNummer = new javax.swing.JTextField();
        txtPostcode = new javax.swing.JTextField();
        txtStad = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblGD = new javax.swing.JLabel();
        txtDag = new javax.swing.JTextField();
        btnToevoegenPrive = new javax.swing.JButton();
        cBox = new javax.swing.JComboBox();
        lblSlash1 = new javax.swing.JLabel();
        txtMaand = new javax.swing.JTextField();
        txtJaar = new javax.swing.JTextField();
        lblSlash2 = new javax.swing.JLabel();
        btnTerug = new javax.swing.JButton();
        txtFile = new javax.swing.JTextField();
        btnFile = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNaam.setText("Naam");

        lblBTW.setText("BTW");

        jLabel3.setText("Straat");

        jLabel4.setText("Nr");

        jLabel5.setText("Postcode");

        jLabel6.setText("Stad");

        txtNaam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNaamActionPerformed(evt);
            }
        });

        lblEmail.setText("E-mailadres");

        lblGD.setText("Geboortedatum");

        btnToevoegenPrive.setText("Bewerken");
        btnToevoegenPrive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToevoegenPriveActionPerformed(evt);
            }
        });

        cBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Privé", "Bedrijf" }));
        cBox.setToolTipText("");
        cBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxActionPerformed(evt);
            }
        });

        lblSlash1.setText("/");

        lblSlash2.setText("/");

        btnTerug.setText("Sluiten");
        btnTerug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerugActionPerformed(evt);
            }
        });

        txtFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileActionPerformed(evt);
            }
        });

        btnFile.setText("...");
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });

        jButton2.setText("Spaarkaarten");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblNaam)
                            .add(lblBTW))
                        .add(23, 23, 23)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtNaam)
                            .add(txtBTW))
                        .add(47, 47, 47))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(txtStraat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 263, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtNummer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(txtPostcode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(35, 35, 35)
                                .add(jLabel6)
                                .add(18, 18, 18)
                                .add(txtStad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE))))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, cBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lblEmail)
                                    .add(lblGD))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(txtEmail, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .add(layout.createSequentialGroup()
                                        .add(txtDag, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(lblSlash1)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(txtMaand, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(2, 2, 2)
                                        .add(lblSlash2)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(txtJaar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(txtFile))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(btnFile)))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(btnTerug)
                        .add(134, 134, 134)
                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(btnToevoegenPrive, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .add(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(cBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblNaam)
                    .add(txtNaam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblBTW)
                    .add(txtBTW, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(txtStraat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtNummer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jLabel6)
                    .add(txtPostcode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtStad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblEmail)
                    .add(txtEmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblGD)
                    .add(txtDag, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblSlash1)
                    .add(txtMaand, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtJaar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblSlash2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtFile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnFile))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 7, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnToevoegenPrive)
                    .add(btnTerug)
                    .add(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNaamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNaamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNaamActionPerformed

    private void cBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxActionPerformed
        Object selected = cBox.getSelectedItem();
        if(selected.toString().equals("Privé"))
        {
            isBedrijf = false;
            lblBTW.setVisible(false);
            txtBTW.setVisible(false);
            txtDag.setVisible(true);
            txtMaand.setVisible(true);
            txtJaar.setVisible(true);
            lblSlash1.setVisible(true);
            lblSlash2.setVisible(true);
            lblGD.setVisible(true);
        }
        else if(selected.toString().equals("Bedrijf"))
        {
            isBedrijf = true;
            lblBTW.setVisible(true);
            txtBTW.setVisible(true);
            txtMaand.setVisible(false);
            txtJaar.setVisible(false);
            lblSlash1.setVisible(false);
            lblSlash2.setVisible(false);
            lblGD.setVisible(false);
        }
    }//GEN-LAST:event_cBoxActionPerformed

    private void btnToevoegenPriveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToevoegenPriveActionPerformed
        Pattern tf3 = Pattern.compile("\\d{1,8}");
        Pattern tf4 = Pattern.compile("\\d{4}");
        Pattern tf5 = Pattern.compile("\\d{2}");
        Pattern tf6 = Pattern.compile("\\d{10}");
        
        Matcher matcher3 = tf3.matcher(txtNummer.getText());
        Matcher matcher4 = tf4.matcher(txtPostcode.getText());
        Matcher matcher5 = tf5.matcher(txtDag.getText());
        Matcher matcher6 = tf5.matcher(txtMaand.getText());
        Matcher matcher7 = tf4.matcher(txtJaar.getText());
        Matcher matcher8 = tf6.matcher(txtBTW.getText());
        
        if(txtNaam.getText().equals("") || txtNaam.getText().length() > 64)
        {
            JOptionPane.showMessageDialog(guiNK, "Naam invullen", "Naam invullen", JOptionPane.ERROR_MESSAGE);
        }
        else if(isBedrijf == true && !matcher8.matches())
        {
            JOptionPane.showMessageDialog(guiNK, "BTW-nummer invullen", "BTW-nummer invullen", JOptionPane.ERROR_MESSAGE);
        }               
        else if(txtStraat.getText().equals("") || txtStraat.getText().length() > 128)
        {
            JOptionPane.showMessageDialog(guiNK, "Straat invullen", "Straat invullen", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtNummer.getText().equals("") || !matcher3.matches())
        {
            JOptionPane.showMessageDialog(guiNK, "Nummer invullen", "Nummer invullen", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtPostcode.getText().equals("") || !matcher4.matches())
        {
            JOptionPane.showMessageDialog(guiNK, "Postcode invullen", "Postcode invullen", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtStad.getText().equals("") || txtStad.getText().length() > 64)
        {
            JOptionPane.showMessageDialog(guiNK, "Stad invullen", "Stad invullen", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtEmail.getText().equals("") || txtEmail.getText().length() > 128)
        {
            JOptionPane.showMessageDialog(guiNK, "Email invullen", "Email invullen", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtDag.getText().equals("") && isBedrijf == false || !matcher5.matches())
        {
            JOptionPane.showMessageDialog(guiNK, "Dag invullen", "Dag invullen", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtMaand.getText().equals("") && isBedrijf == false || !matcher6.matches())
        {
            JOptionPane.showMessageDialog(guiNK, "Maand invullen", "Maand invullen", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtJaar.getText().equals("") && isBedrijf == false || !matcher7.matches())
        {
            JOptionPane.showMessageDialog(guiNK, "Jaar invullen", "Jaar invullen", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String naam = txtNaam.getText();
            String straat = txtStraat.getText();
            String nummer = txtNummer.getText();
            String postcode = txtPostcode.getText();
            String stad = txtStad.getText();
            String email = txtEmail.getText();
            int dag = 0;
            int maand = 0;
            int jaar = 0;
            String btw = "";
            if(isBedrijf == false)
            {
                dag = Integer.parseInt(txtDag.getText());
                maand = Integer.parseInt(txtMaand.getText());
                jaar = Integer.parseInt(txtJaar.getText());
            }
            else
            {
                btw = txtBTW.getText();
            }
            int aangemaaktd = ac.getAangD();
            int aangemaaktm = ac.getAangM();
            int aangemaaktj = ac.getAangJ();
            int gespaardepunten = 0;
            int werkelijkepunten = 0;
            boolean vip = false;
            boolean bigspender = false;
            boolean wolverene = false;
            String fotopath = txtFile.getText();
            
            MySQL mySql = new MySQL();
            try 
            {
                mySql.updateAccount(ac.getID(), naam, straat, nummer, postcode, stad, email, btw, isBedrijf, aangemaaktd, aangemaaktm, aangemaaktj, gespaardepunten, werkelijkepunten, dag, maand, jaar, vip, bigspender, wolverene, fotopath);
            } catch (SQLException ex) 
            {
            }
            
            if(fi == true)
            {
                GuiFiliaalIndex guiKI = GuiFiliaalIndex.getInstance();
                setVisible(false);
                guiKI.setVisible(true);
            }
            else
            {
                GuiKlanten guiK = GuiKlanten.getInstance();
                guiK.updateTable();
                setVisible(false);
                guiK.setVisible(true);                
            }
        }                                  
    }//GEN-LAST:event_btnToevoegenPriveActionPerformed

    private void txtFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileActionPerformed

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
        fc = new JFileChooser();
        FileFilter imageFilter = new FileNameExtensionFilter("Images", "jpg", "jpeg", "png", "gif", "bmp");
        fc.setFileFilter(imageFilter);
        fc.setAcceptAllFileFilterUsed(false);
        int returnVal = fc.showOpenDialog(guiNK);
        if (returnVal == JFileChooser.APPROVE_OPTION) 
        {
            File file = fc.getSelectedFile();
            txtFile.setText(file.getPath());
        } else 
        {
            txtFile.setText("");
        }
    }//GEN-LAST:event_btnFileActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GuiSpaarkaarten guiSk = GuiSpaarkaarten.getInstance();
        guiSk.setAccount(ac);
        guiSk.updateTable();
        setVisible(false);
        guiSk.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnTerugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerugActionPerformed
        if(fi == true)
        {
            GuiFiliaalIndex guiKI = GuiFiliaalIndex.getInstance();
            setVisible(false);
            guiKI.setVisible(true);
        }
        else
        {
            GuiKlanten guiK = GuiKlanten.getInstance();
            guiK.updateTable();
            setVisible(false);
            guiK.setVisible(true);                
        }
    }//GEN-LAST:event_btnTerugActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiKlantBew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiKlantBew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiKlantBew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiKlantBew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiKlantBew().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFile;
    private javax.swing.JButton btnTerug;
    private javax.swing.JButton btnToevoegenPrive;
    private javax.swing.JComboBox cBox;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblBTW;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGD;
    private javax.swing.JLabel lblNaam;
    private javax.swing.JLabel lblSlash1;
    private javax.swing.JLabel lblSlash2;
    private javax.swing.JTextField txtBTW;
    private javax.swing.JTextField txtDag;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFile;
    private javax.swing.JTextField txtJaar;
    private javax.swing.JTextField txtMaand;
    private javax.swing.JTextField txtNaam;
    private javax.swing.JTextField txtNummer;
    private javax.swing.JTextField txtPostcode;
    private javax.swing.JTextField txtStad;
    private javax.swing.JTextField txtStraat;
    // End of variables declaration//GEN-END:variables
}
