/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bingo;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonas
 */
public class GuiSpaarkaarten extends javax.swing.JFrame {

    /**
     * Creates new form GuiArtikels
     */
    
    private static final GuiSpaarkaarten guiSK = new GuiSpaarkaarten();
    protected Account ac;
    private DefaultTableModel model;
    ArrayList<Spaarkaart> sList;
    ArrayList<Spaarkaart> curList;

    public static GuiSpaarkaarten getInstance()
    {
        return guiSK;
    }    
    
    public GuiSpaarkaarten() 
    {
        initComponents();
    }

    public void setAccount(Account a)
    {
        this.ac = a;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSpaarkaarten = new javax.swing.JTable();
        btnBewerken = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnTerug = new javax.swing.JButton();
        btnToevoegen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        model = new DefaultTableModel()
        {
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };
        tblSpaarkaarten.setModel(model);
        jScrollPane1.setViewportView(tblSpaarkaarten);

        btnBewerken.setText("Bewerken");
        btnBewerken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBewerkenActionPerformed(evt);
            }
        });

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnTerug.setText("Terug");
        btnTerug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerugActionPerformed(evt);
            }
        });

        btnToevoegen.setText("Toevoegen");
        btnToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToevoegenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTerug)
                        .addGap(51, 51, 51)
                        .addComponent(btnToevoegen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBewerken))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBewerken)
                    .addComponent(btnTerug)
                    .addComponent(btnToevoegen))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBewerkenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBewerkenActionPerformed
        System.out.println(tblSpaarkaarten.getSelectedRow());
        System.out.println(curList.get(tblSpaarkaarten.getSelectedRow()).getNaam());  
        GuiSpaarkaartBew guiSkB = GuiSpaarkaartBew.getInstance();
        if(curList.isEmpty())
        {
            guiSkB.setSk(sList.get(tblSpaarkaarten.getSelectedRow()));
            System.out.println("CL: " + curList.get(tblSpaarkaarten.getSelectedRow()).getNaam());
        }
        else
        {
            guiSkB.setSk(curList.get(tblSpaarkaarten.getSelectedRow()));
            System.out.println("AL: " + sList.get(tblSpaarkaarten.getSelectedRow()).getNaam());
        }
        setVisible(false);
        guiSkB.setVisible(true);
    }//GEN-LAST:event_btnBewerkenActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String search = txtSearch.getText();
        System.out.println(search);
        if(search.equals(""))
        {
            initTable(sList);
        }
        else
        {
            ArrayList<Spaarkaart> zkList = zoekSpaarkaarten(search);
            initTable(zkList);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    public void updateTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblSpaarkaarten.getModel();
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--)
        {
            model.removeRow(i);
        }
        MySQL mySQL = new MySQL();
        sList = mySQL.getSpaarkaarten(ac.getID());
        curList = sList;
        model.setColumnIdentifiers(new String[]{"ID", "Naam", "Voornaam", "Accountnaam"});
        for(Spaarkaart s : sList)
        {
            model.addRow(new Object[]{s.getSId(), s.getSNaam(), s.getVoornaam(), s.getNaam()});
        }
    }
    
    private void btnTerugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerugActionPerformed
        GuiKlantBew guiKB = GuiKlantBew.getInstance();
        guiKB.setAccount(ac);
        setVisible(false);
        guiKB.setVisible(true); 
    }//GEN-LAST:event_btnTerugActionPerformed

    private void btnToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToevoegenActionPerformed
        GuiNieuweSpaarkaart guiNSk = GuiNieuweSpaarkaart.getInstance();
        guiNSk.setAccount(ac);
        guiNSk.setNieuw(false);
        setVisible(false);
        guiNSk.setVisible(true);
    }//GEN-LAST:event_btnToevoegenActionPerformed

    public ArrayList<Spaarkaart> zoekSpaarkaarten(String kw)
    {
        ArrayList<Spaarkaart> zkList = new ArrayList<Spaarkaart>();
        for(Spaarkaart s : sList)
        {
            if(s.getSNaam().toLowerCase().startsWith(kw.toLowerCase()) || s.getVoornaam().toLowerCase().startsWith(kw.toLowerCase()) || s.getNaam().toLowerCase().startsWith(kw.toLowerCase()))
            {
                zkList.add(s);
            }
        }
        return zkList;
    }
    
    public void initTable(ArrayList<Spaarkaart> aList)
    {
        DefaultTableModel model = (DefaultTableModel) tblSpaarkaarten.getModel();
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--)
        {
            model.removeRow(i);
        }
        for(Spaarkaart s : sList)
        {
            model.addRow(new Object[]{s.getSId(), s.getSNaam(), s.getVoornaam(), s.getNaam()});
            this.curList = sList;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiSpaarkaarten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiSpaarkaarten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiSpaarkaarten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiSpaarkaarten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiSpaarkaarten().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBewerken;
    private javax.swing.JButton btnTerug;
    private javax.swing.JButton btnToevoegen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSpaarkaarten;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
