/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bingo;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gmavdamm
 */
public class GuiWinkelVerkopenPunten extends javax.swing.JFrame {

    /**
     * Creates new form GuiWinkelRapportAssortiment
     */
    
    private static final GuiWinkelVerkopenPunten guiWRA = new GuiWinkelVerkopenPunten();
    private DefaultTableModel model;
    private Winkel wi;

    public static GuiWinkelVerkopenPunten getInstance()
    {
        return guiWRA;
    }
    
    public void setWinkel(Winkel wn)
    {
        this.wi = wn;
        lblNaam.setText(wi.getWinkelNaam());
    }
    
    public GuiWinkelVerkopenPunten() 
    {
        initComponents();
    }
    
    public void updateTable()
    {
        MySQL sql = new MySQL();
        ArrayList<Verkopen> verkopen = sql.getVerkopenWinkelPunten(wi.getWinkelID());
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--)
        {
            model.removeRow(i);
        }
        for(Verkopen v : verkopen)
        {
            model.addRow(new Object[]{v.getId(), v.getNaam(), v.getDatum(), v.getHoev(), v.getPuntenkopen()});
            
        }
        model.addRow(new Object[]{"","","", "",sql.getVerkopenWinkelPuntenPK(wi.getWinkelID())});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNaam = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVerkopen = new javax.swing.JTable();
        btnExporteren = new javax.swing.JButton();
        btnTerug = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));

        lblNaam.setText("Naam");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNaam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNaam)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Verkopen met punten"));

        model = new DefaultTableModel()
        {
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };
        tblVerkopen.setModel(model);
        model.setColumnIdentifiers(new String[]{"ID", "Naam","Datum", "Hoeveelheid", "Punten gekocht"});
        jScrollPane1.setViewportView(tblVerkopen);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnExporteren.setText("Exporteren");
        btnExporteren.setActionCommand("");
        btnExporteren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExporterenActionPerformed(evt);
            }
        });

        btnTerug.setText("Terug");
        btnTerug.setActionCommand("");
        btnTerug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerugActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(btnTerug, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExporteren, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExporteren)
                    .addComponent(btnTerug))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExporterenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExporterenActionPerformed
       MySQL sql = new MySQL();
        ArrayList<Verkopen> verkopen = sql.getVerkopenWinkelPunten(wi.getWinkelID());
           
        String str = "%11s\t%32s\t%10s\t%11s\t%12s\r\n";
        str = str.format(str, "ID", "Naam", "Datum", "Hoeveelheid", "Punten kop");

        double totaal = 0.0;
       
        for(Verkopen v : verkopen)
        {
            String stl = "";
            String st = "";
            stl = "%11d\t%32s\t%10s\t%11d\t%10.2f\r\n";
            st = st.format(stl, v.getId(), v.getNaam(), v.getDatum(), v.getHoev(), v.getPuntenkopen());
            str += st;
            totaal += v.getPuntenkopen();
        }
       
        str += "\t\t\t\t\t\t\t\t\t\t   " + "_______________" + "\r\n";
        String stb = "";
        stb = stb.format("\t\t\t\t\t\t\t\t\t\t\t%10.2f", totaal);
        str += stb;
        
        String file = wi.getNaam() + " VerkopenMetPunten.txt";
        File f = new File(file);
        if(f.exists())
        {
            f.delete();
        }
        PrintWriter best = null;
        try
        {
            best = new PrintWriter(new FileOutputStream(file, true));
            best.append(str);
            best.flush();
            best.close();
        }
        catch(IOException e)
        {
            try
            {
                best.close();
            }
            catch(Exception ex)
            {
                 
            }
            e.printStackTrace();
        }  
        JOptionPane.showMessageDialog(guiWRA, "Rapport geëxporteerd.", "Rapport geëxporteerd.", JOptionPane.INFORMATION_MESSAGE);        
    }//GEN-LAST:event_btnExporterenActionPerformed

    private void btnTerugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerugActionPerformed
        GuiWinkelIndex guiWI = GuiWinkelIndex.getInstance();
        setVisible(false);
        guiWI.setVisible(true);
    }//GEN-LAST:event_btnTerugActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExporteren;
    private javax.swing.JButton btnTerug;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNaam;
    private javax.swing.JTable tblVerkopen;
    // End of variables declaration//GEN-END:variables
}
